### ISSUE TITLE
При запуске карта фокусируется на Красной Площади

### ISSUE THREAD

**Issue by elagin** [elagin/motobatClient#22]
вне зависимости от расположения. При нажатии кнопки в правом верхем углу карта фокусируется правильно.

**Comment by elagin** [comment]
Потому, что в createMap Location не содержит координат.

**Comment by elagin** [comment]
М.б. тогда при первом вызове FusionLocationListener попытатьсяя еще раз переместить карту. Вот только не красиво получиться, если юзер уже успеет начать скроллить карту :)

**Comment by rjhdby** [comment]
Исправлено
https://github.com/elagin/motobatClient/commit/ba0cfa2f01569a8f349fd78917a79255270f7ea9

**Comment by elagin** [comment]
Спасибо.
