### ISSUE TITLE
Логотип

### ISSUE THREAD

**Issue by elagin** [elagin/motobatClient#3]
Пока приделал http://www.clipartpanda.com/clipart_images/png-small-medium-large-40864410 который на маленьком разрешении похож на рыбу, выглядывающую из воды.
Да не совсем в тему, мало того, что не мотошлем, да еще фуражка не российского образца.

Есть такой вариант: https://pixabay.com/ru/%D0%BA%D1%80%D0%B0%D1%81%D0%BD%D1%8B%D0%B9-%D1%81%D0%B2%D0%B5%D1%82-%D0%BC%D0%B8%D0%B3%D0%B0%D0%B5%D1%82-%D0%BA%D1%81-%D0%BF%D0%BE%D0%BB%D0%B8%D1%86%D0%B8%D1%8F-33645/

А такое можно самим нарисовать: https://www.iconfinder.com/icons/170696/agitation_alarm_alert_ambulance_anxiety_bell_buzz_buzzer_danger_dismay_distrurbance_emergency_exclamation_fire_foghom_hoot_hooter_hospital_lamp_light_loud_medicine_police_signal_siren_syren_trouble_warning_worry_icon#size=128

**Comment by rjhdby** [comment]
Я жену попросил в карандаше набросать. Потом сфотаю и в вектор переведу.

**Comment by elagin** [comment]
А м.б. она сразу вектор набросает? Могу перо дать, если найду :)
