### ISSUE TITLE
Ошибка опредедения адреса

### ISSUE THREAD

**Issue by rjhdby** [elagin/motobatClient#38]
https://play.google.com/apps/publish/?dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.IndexOutOfBoundsException&tf=ArrayList.java&tc=java.util.ArrayList&tm=throwIndexOutOfBoundsException&nid&an&c&s=new_status_desc

**Comment by elagin** [comment]
Не в том проекете.
