### ISSUE TITLE
Применение intentService

### ISSUE THREAD

**Issue by elagin** [elagin/motobatClient#52]

**Comment by rjhdby** [comment]
к чему?

**Comment by elagin** [comment]
К обмену данным с сервером. Надо через него все делать, тогда не страшно, если активити будет пересоздано. Например при повороте экрана. Это правильный паттерн для таких вещей. Посмотри https://github.com/elagin/motobatClient/tree/IntentService еще не готово, но уже более-менее понятно.

**Comment by elagin** [comment]
Готово: https://github.com/elagin/motobatClient/commit/9648373ff9cbc2e7d7c73c78233f88b21f1ecc21
