### ISSUE TITLE
java.io.FileNotFoundException: global.properties

### ISSUE THREAD

**Issue by rjhdby** [elagin/motobatClient#8]
```
private void makeGlobal() {
    InputStream is;
    try {
        String GLOBAL = "global.properties";
        is = as.open(GLOBAL);  //51 строка
        global = read(is);
    } catch (IOException e) {
        e.printStackTrace();
    }
}
```

java.io.FileNotFoundException: global.properties
android.content.res.AssetManager.openAsset(Native Method)
android.content.res.AssetManager.open(AssetManager.java:328)
android.content.res.AssetManager.open(AssetManager.java:302)
**com.mototime.motobat.utils.Props.makeGlobal(Props.java:51)**
com.mototime.motobat.utils.Props.<init>(Props.java:25)
com.mototime.motobat.MyApp.getProps(MyApp.java:51)
com.mototime.motobat.network.HTTPClient.request(HTTPClient.java:68)
com.mototime.motobat.network.HTTPClient.doInBackground(HTTPClient.java:46)
com.mototime.motobat.network.HTTPClient.doInBackground(HTTPClient.java:32)

**Comment by elagin** [comment]
Я так и не понял как проперти к проекту добавлять.

**Comment by rjhdby** [comment]
Пофиксил ddbfcc7eaa07adcd6c8866f2f9925e33fae855b4
