### ISSUE TITLE
Начало создания точки прямо из главного экрана.

### ISSUE THREAD

**Issue by elagin** [elagin/motobatClient#9]
Сейчас мы при запуске наблюдаем карту.
Если хотим создать точку, то нажимаем "создать точку", переходим в первый экран создания точки с картой, затем жмем "подтвердить адрес"  переходим на второй экран для описания точки.

Так может быть в главное окно добавить "прицел". Тогда при нажатии "создать точку" координаты уже есть и можно сразу заполнять второй экран с описанием.

**Comment by rjhdby** [comment]
вполне здраво

**Comment by rjhdby** [comment]
Не по кнопке, а по onLongClick на карте

**Comment by elagin** [comment]
По мне лучше кнопка. Ее сразу видно, а лонг-клик нужно либо в документации прочитать, либо догадаться.

**Comment by rjhdby** [comment]
На яндекс-картах по лонгклику сделано(ну и прозрачная кнопочка слева прям поверх карты)

**Comment by elagin** [comment]
Я.карт у меня нет, а на я.навигаторе по долгому клику происходит центрирование карты и появляется поверх карты панель с кнопками-действиями. Но у нас действие-то пока одно.

Как же тогда, сделал долгий клик и сразу в окно создания улетел? А вдруг ты скролил просто неудачно. Мне кажется кнопка, по которой происходит переход в создание точки это удобно и нет ложных срабатываний.

**Comment by rjhdby** [comment]
ненене. Парадигма такая - только один экран(ну кроме настроек и авторизации), на нем все и происходит, через попапы(красивые).
Ложные срабатывания всегда есть, как управляющие инструменты не располагай. Только одно дело тыркнуть в карту мимо попапа и он закроется, а другое - отправлять в отдельный экран.

**Comment by elagin** [comment]
А т.е. по клику в карту всплывет попап, по тыку в которой будет переход на создание точки? Да так будет хорошо.

**Comment by rjhdby** [comment]
Да даже перехода в создание точки не нужно - в бабле 2 ряда по три пиктограммы и кнопка Создать.

**Comment by rjhdby** [comment]
Не актуально
